
package webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Wed Aug 31 12:01:06 PKT 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "executeDMLRequest", namespace = "http://webservices/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeDMLRequest", namespace = "http://webservices/", propOrder = {"arg0", "arg1", "arg2"})

public class ExecuteDMLRequest {

    @XmlElement(name = "arg0")
    private dml.def.DMLTransWrapper arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;

    public dml.def.DMLTransWrapper getArg0() {
        return this.arg0;
    }

    public void setArg0(dml.def.DMLTransWrapper newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

}

