
package webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Wed Aug 31 12:01:06 PKT 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "executeDMLRequestResponse", namespace = "http://webservices/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeDMLRequestResponse", namespace = "http://webservices/")

public class ExecuteDMLRequestResponse {

    @XmlElement(name = "return")
    private dml.def.DMLTransWrapper _return;

    public dml.def.DMLTransWrapper getReturn() {
        return this._return;
    }

    public void setReturn(dml.def.DMLTransWrapper new_return)  {
        this._return = new_return;
    }

}

