
package webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Wed Aug 31 12:01:06 PKT 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "loadUserRoleWiseMenuesResponse", namespace = "http://webservices/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loadUserRoleWiseMenuesResponse", namespace = "http://webservices/")

public class LoadUserRoleWiseMenuesResponse {

    @XmlElement(name = "return")
    private java.util.List<app.beans.Menus> _return;

    public java.util.List<app.beans.Menus> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<app.beans.Menus> new_return)  {
        this._return = new_return;
    }

}

