
package webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Wed Aug 31 12:01:06 PKT 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "loadDefinitionData", namespace = "http://webservices/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loadDefinitionData", namespace = "http://webservices/")

public class LoadDefinitionData {

    @XmlElement(name = "arg0")
    private app.beans.LoginEmployee arg0;

    public app.beans.LoginEmployee getArg0() {
        return this.arg0;
    }

    public void setArg0(app.beans.LoginEmployee newArg0)  {
        this.arg0 = newArg0;
    }

}

